version: '3'
services:
    web:
        build: ./etc/nginx
        container_name: ${APP_NAME}_nginx
        ports:
            - "8080:80"
            - "81:443"
        restart: always
        volumes:
            - "./etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./etc/nginx/app_${APP_TYPE}.conf:/etc/nginx/sites-available/application.conf"
            - "./etc/nginx/app_${APP_TYPE}.conf:/etc/nginx/sites-enabled/application"
            - "./etc/ssl:/etc/ssl"
            - ${APP_PATH}:/var/www/html
        depends_on:
            - php
            - database
    php:
        build: ./etc/php
        container_name: ${APP_NAME}_php
        ports:
            - 9000:9000
        links:
            - database:mysqldb
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - ${API_PATH}:/var/www/api
    database:
        image: mysql
        container_name: ${APP_NAME}_mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3300:3306
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
